### ISSUE TITLE
Pagination links

### ISSUE THREAD

**Issue by soufianeh** [miguelgrinberg/APIFairy#14]
How would you go about implementing pagination links for an endpoint?

Let's say I have this endpoint: `/api/users`

```
from apifairy import arguments

class PaginationSchema(ma.Schema):
   page = ma.Int(missing=1)
   per_page = ma.Int(missing=10)

class UserSchema(ma.Schema):
    id = ma.Int()
    username = ma.Str(required=True)
    email = ma.Str(required=True)

@app.route('/api/users/')
@arguments(PaginationSchema)
@response(UserSchema(many=True))
def get_users(pagination, id):
    page = pagination['page']
    per_page = pagination['per_page']
   
   return User.query.paginate(page, per_page, False).items
```

My goal is to have pagination links in my response, something like this:
```
'_links': {
     'next': '/api/users?page=3,
     'prev': '/api/users?page=1
}
```

**Comment by miguelgrinberg** [comment]
Are you asking about the actual implementation, not just the OpenAPI documentation? That is not something this package is concerned about, for that you have to use Flask-Marshmallow, probably `ma.Hyperlinks`, which you would add to the schema of your response. There is an example in the [Flask-Marshmallow docs](https://pypi.org/project/flask-marshmallow/).

**Comment by soufianeh** [comment]
@miguelgrinberg Yes, I am already using `ma.Hyperlinks` for other stuff, my issue is with having a schema that is aware of the current page, and thus being able to get next & prev. I will close this as it is posted in the wrong repo. Thanks.
