### ISSUE TITLE
templates folder is missing 

### ISSUE THREAD

**Issue by itsDrac** [miguelgrinberg/APIFairy#2]
I installed apifairy using `pip` and wrote a simple flask app. Afterwards, when i put a get request in `localhost/docs` it throws an error 

`raise TemplateNotFound(template)`

when i looked in apifary source folder inside virtualenv (for me it's `venv/lib/python3.7/site-packages/apifairy`)

i couldn't find `templates` folder in there

to solve this error i manually have to download templates folder from github and placed it in there it works fine

**Comment by edmondchuc** [comment]
I was just about to post the same issue.

**Comment by miguelgrinberg** [comment]
Sorry about this. It's now fixed in release 0.6.1. Please upgrade from pypi.

**Comment by yufernando** [comment]
This seems to still be the case in version 0.8.0. The templates folder is missing.

**Comment by greyli** [comment]
> This seems to still be the case in version 0.8.0.

This will be fixed with #34.

**Comment by miguelgrinberg** [comment]
@yufernando sorry about that. I lost the setting to included these files when I restructured the package in the 0.8.0 release. The 0.8.2. build fixes it, hopefully for good!

**Comment by yufernando** [comment]
It's fixed now. Thank you both! I'm a big fan of your work @miguelgrinberg.
