### ISSUE TITLE
making documentation recognize two parameters in an endpoint route

### ISSUE THREAD

**Issue by jreich218** [miguelgrinberg/APIFairy#22]
Miguel,

This is a much needed library! Thanks for sharing this.

I just have a quick question. How would we get the extension to pickup two parameters in a route like this:

`@bp.route("/<int:id>/<int:version>", methods=["GET"])`

When I elect to use the Swagger UI in my configuration, and select "Try it out" in Swagger, the Swagger UI only asks for the version value. (So there is no way that I'm aware of to enter the id from the Swagger UI).

This isn't so much about the Swagger UI, I'm more just wondering how we make the extension recognize both parameters. Should we use the @arguments decorator? Or is there a way for the extension to "just know" that there are two parameters in the route/endpoint?

Thanks!

**Comment by miguelgrinberg** [comment]
Yeah, I think this is just a bug. It was fixed, but I haven't made a release yet. If you want to try it right away, install the package directly from this GitHub repo. In any case, I now realize that this is important enough that needs to be released, so there'll be a new release out in a little bit.

**Comment by miguelgrinberg** [comment]
v0.7.0 is now released. Please reopen if you still find issues.

**Comment by jreich218** [comment]
Works perfectly!
