### ISSUE TITLE
Multiple API Versions

### ISSUE THREAD

**Issue by ericsouza** [miguelgrinberg/APIFairy#23]
Hey Miguel! Thanks for this extensions. I have a question, how would I manage multiple API versions? I'm using a blueprint for each version of my API (don't know if it's the best approach), how can I get a the docs for each version?

**Comment by miguelgrinberg** [comment]
Were you hoping to have separate documentation sites for each version? The extension currently generates a single endpoint for all your docs. If you have something like `/v1/...` and `/v2/...` these prefixes should be included in the docs.

**Comment by ericsouza** [comment]
I was able do to what I need just by using a blueprint for each version of my api. Thanks again! :)
