### ISSUE TITLE
New_Android_OS_Requirements

### ISSUE THREAD

**Issue by Itzshivam1908** [miguelgrinberg/APIFairy#24]
Some your code isn't support for the new android version i.e., Android 11 & 12 .I'm unable to use your codes in this new versions .

**Comment by miguelgrinberg** [comment]
@Itzshivam1908 I don't know what you mean. This is a Python project, nothing to do with Android.

**Comment by Itzshivam1908** [comment]
@miguelgrinberg  I meant that this code isn't work properly on latest android OS and I have also an python environment . Your code run on my PC but not on android device.May you tell me, what reason behind on it?

**Comment by miguelgrinberg** [comment]
I don't know. Android is not a supported platform, I have never intended this project to run on Android. I'm not even familiar with how you run Python code there.

**Comment by Itzshivam1908** [comment]
> I don't know. Android is not a supported platform, I have never intended this project to run on Android. I'm not even familiar with how you run Python code there.

@miguelgrinberg 
# Visual Studio Code
May I run your code on this application or linux OS?
Is your codes support visual environment?

**Comment by miguelgrinberg** [comment]
I'm sorry, but I don't understand what you are asking. APIFairy is a library that you use in your application. You can use any IDE to write your application code, that is not related to APIFairy.

**Comment by Itzshivam1908** [comment]
#Permission_Restrictions_On_Android_OS
@miguelgrinberg Ok,Now I understand that your APIFairy library is not work properly work on android because android has some permissions striction.That's why I'm unable to run this but I run it by rooting my phone .Then, It works properly .
