### ISSUE TITLE
how to use 2 schemas for 1 api endpoint (returning error details)

### ISSUE THREAD

**Issue by spacekbnueve** [miguelgrinberg/APIFairy#26]
My API endpoint returns users so I used `@response` with the user schema.   

Now in case of error I would also like to return something like:   

```
{
  "error": {
    "message": "Lorem ipsum", 
    "type": "foobar"
  }
}
```

Obviously that does not match the user schema and my endpoint returns `{}` when an error happens.   
What would be the best way to achieve what I want to do ?

Thanks for your help.

**Comment by miguelgrinberg** [comment]
To return an error you have to use the error handling support in Flask. In your view function you raise an exception, and then you create an error handler for it that returns the error response (which can also be based on a schema, if you like).

**Comment by spacekbnueve** [comment]
That's exactly what I needed, thanks !
