### ISSUE TITLE
How to group api endpoints by a category

### ISSUE THREAD

**Issue by spacekbnueve** [miguelgrinberg/APIFairy#28]
How do you group api endpoints by a category as seen in your screenshot:

![image](https://user-images.githubusercontent.com/86686351/124190237-ed384b00-da8f-11eb-9485-94934d90d132.png)

**Comment by miguelgrinberg** [comment]
The categories are the blueprints that you define in your application.

**Comment by spacekbnueve** [comment]
Got it thanks.
