### ISSUE TITLE
How to specify type when using custom marshmallow field

### ISSUE THREAD

**Issue by spacekbnueve** [miguelgrinberg/APIFairy#29]
I'm using mongodb and I created a custom marschmallow field to serialize and deserialize mongodb ids which are ObjectId.   
Basically they get serialize to string when returned by the API.   
However in the documentation they appear as type null:

![image](https://user-images.githubusercontent.com/86686351/124305575-47d6b300-db33-11eb-9cb1-e5d26c175f99.png)

Would you know what I should do so that the shown type is string ?

Below the code for the custom field:

```
class ObjectId(fields.Field):
    '''
    Used to serialize and deserialize mongodb ObjectId with marshmallow
    '''
    def _deserialize(self, value, attr, data, **kwargs):
        try:
            return bson.ObjectId(value)
        except Exception:
            raise ValidationError("invalid ObjectId `%s`" % value)

    def _serialize(self, value, attr, obj, **kwargs):
        if value is None:
            return ''
        return str(value)
```

**Comment by miguelgrinberg** [comment]
This package does not really manage the generation of the openapi documentation, this is done by the `apispec` package. But as it happens, they have documentation for how to solve your problem: https://apispec.readthedocs.io/en/latest/using_plugins.html?highlight=custom%20field#custom-fields.

**Comment by spacekbnueve** [comment]
Thanks !
