### ISSUE TITLE
Incorrect rendering of long descriptions

### ISSUE THREAD

**Issue by arunksoman** [miguelgrinberg/APIFairy#30]
While rendering some long descriptions I could see some additional spaces which is not stripped down (If we are following default indentation in docstring). So I forked and tried instead [these lines](https://github.com/miguelgrinberg/APIFairy/blob/268d5e9a5d58cdb53abff0d75f20289ac7c897de/src/apifairy/core.py#L228)

something like:

```
if len(docs) > 1:
    operation['description'] = '\n'.join([''.join(docstr).strip() for docstr in docs[1:]])
```

Then it works fine. Can you please check that out? I am not making PR because there might be a better way to solve this issue.

**Comment by miguelgrinberg** [comment]
@arunksoman Can you give the main branch of this repository a try? Let me know if those extra spaces are gone for you. Thanks.
