### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by spacekbnueve** [miguelgrinberg/APIFairy#35]
How would you document file upload using APIFairy ?

I'm using Flask and something like:

`file = request.files['file']`

Would you put the file content in a JSON and use `@body` ?

**Comment by miguelgrinberg** [comment]
My focus so far has been on documenting JSON APIs, so I did not implement any decorators or other shortcuts to represent form submissions and file uploads. You can define a processing callback with the `process_apispec` decorator, and in that function you can edit the generated OpenAPI specification to include the file upload (documentation is [here](https://swagger.io/docs/specification/describing-request-body/file-upload/)).

I will be looking at adding form submissions and uploads  at some point. Will keep this issue open to remind me of this.

**Comment by spacekbnueve** [comment]
Sounds good, thanks.

Posting my snippet as example:

```python
@apifairy.process_apispec
def edit_apispec(apispec):
    file_upload_spec = {
        "content": {
          "multipart/form-data": {
            "schema": {
              "type": "object",
              "properties": {
                "file": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          }
        }
      }
    apispec['paths']['/pet/{petId}/uploadImage']['post']['requestBody'] = file_upload_spec
    return apispec
```

**Comment by markalovell-git** [comment]
@spacekbnueve - I'm new to apifairy/marshmallow. Any chance you could show the snippet above in context? Do you have a code example you could post that shows the above snippet in a functioning program? Specifically, what is the 'apispec' you're passing into the `edit_apispec` function, and what is it returning?

**Comment by miguelgrinberg** [comment]
> what is the 'apispec' you're passing into the edit_apispec function, and what is it returning?

See the [process_apispec](https://apifairy.readthedocs.io/en/latest/apifairy_class.html#apifairy-process-apispec) decorator in the documentation. Hopefully that will give you the context you are missing.

**Comment by aderbas** [comment]
Following the tip that the @spacekbnueve  mentioned, I created the function below. In the documentation everything was ok, but when I make the request for the endpoint I get the error: ``marshmallow.exceptions.ValidationError: {'_schema': ['Invalid input type.']}``

```python
@apifairy.process_apispec
def apispec_processor(apispec):
    """Edit API Spec."""
    file_upload_spec = {
        "content": {
            "multipart/form-data": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "log_final": {
                            "format": "binary",
                            "type": "string"
                        },
                        "log_summary": {
                            "format": "binary",
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
    apispec['paths'][UPLOAD_ENDPOINT]['post']["requestBody"] = file_upload_spec

    return apispec
```
Sorry for the newbie question.

**Comment by miguelgrinberg** [comment]
@aderbas Did you use any decorators on the upload endpoint definition?
