### ISSUE TITLE
Marking a Request Body Object as required

### ISSUE THREAD

**Issue by pjb1008** [miguelgrinberg/APIFairy#37]
Hi,

I notice that when I use `@body(MyObjSchema)`, and then use the schema generated by APIFairy to generate a python client, I'm getting definitions like: `def my_operation(request_body=Optional[MyObj] = None)` instead of my intended `my_operation(request_body=MyObj)`.

The OpenAPI 3 Request Body Object has an optional parameter, `required`, which defaults to false.
APIFairy doesn't set this parameter, hence the extra qualifier.

Here is the code that generates the Request Body Object:
```
 		if view_func._spec.get('body'):
                    operation['requestBody'] = {
			'content': {
                            'application/json': {
				'schema': view_func._spec['body'],
                            }
			}
                    }
```

Would it be possible to add an option to the body decorator to feed through to this part of the API generator?

**Comment by miguelgrinberg** [comment]
I have added the required attribute. I don't think this needs to be an option, it would be a strange design decision (I think) to allow for an optional body, and the validation doesn't even support that.

Can I ask you to retest and confirm you get the correct client generated now? Thanks!

**Comment by pjb1008** [comment]
Thanks for the super quick response. Confirmed as working.
