### ISSUE TITLE
Provide support for JWT auth

### ISSUE THREAD

**Issue by suneel944** [miguelgrinberg/APIFairy#38]
Actual:
Current implementation only works with basic auth and the decorator authentication specifically uses flask_httpauth.
Expected:
The authentication decorator should provide option to use jwt token validation

**Comment by miguelgrinberg** [comment]
The authentication decorator in this package is supposed to create the auth section of the OpenAPI. It is not supposed to actually do any authentication work. So what you say that is "expected" is really wrong, as this package was never designed to do auth or actually anything other than creating the documentation site.

Another thing you got wrong. Flask-HTTPAuth supports basic, digest and token authentication.

If you don't want to use Flask-HTTPAuth in your project, then a valid request would be to expect the authentication decorator to work with a different auth extension for Flask. But this package is never going to support auth itself.

**Comment by suneel944** [comment]
Ok got it thank you.  You can close the issue if it is doesn't fitting the project main goals

**Comment by suneel944** [comment]
So could you guide on which api documentation to proceed with when jwt token based validation is being used and project structure is similar to celery redis implementation what had been demonstrated by you

**Comment by miguelgrinberg** [comment]
This is what I use: https://flask-httpauth.readthedocs.io/en/latest/#token-authentication-example.

Flask-HTTPAuth does not work with a specific type of token, it just lets you provide the logic to do the validation, so you can use it with JWT or with any other kind of token.
