### ISSUE TITLE
Explanation to the error situation

### ISSUE THREAD

**Issue by eadomenech** [miguelgrinberg/APIFairy#4]
The api must include an entity or json that contains an explanation to the error situation. For example, a 400 because a field is missing or a 400 because a tuple with the same value of a field already exists, etc. Is it possible to configure the other_responses decorator for it?

**Comment by eadomenech** [comment]
This decorator does not perform any action other than adding the additional responses to the documentation.

**Comment by miguelgrinberg** [comment]
The error response includes a `messages` dictionary with all the errors found during validation.
