### ISSUE TITLE
Question: Secure Documentation without core.py init_app override?

### ISSUE THREAD

**Issue by jorgelaranjo** [miguelgrinberg/APIFairy#41]
If we want the `docs` `blueprint` secure behind a login / password (for a private/non-public API), other than a total override of the `core.py` `init_app` is there a better way to override that blueprint and add a decorator to it?

**Comment by miguelgrinberg** [comment]
Note that the docs endpoint does not render anything that is sensitive. This endpoint just renders your chosen documentation viewer. The endpoint that has your API's details is the one that returns the JSON specification.

If you want to have security on these endpoints, you can disable the endpoints created by APIFairy and define your own. The `/docs` endpoint just uses open source documentation renderers, and the `/apispec.json` endpoint just returns `apifairy.apispec`.

I would imagine most API projects are not going to have a `@login_requred` decorator that they can use for this, or even a login form, so I'm not sure how common your request is. But I would be open to configure custom decorators to be added to these endpoints if that helps.

**Comment by jorgelaranjo** [comment]
> Note that the docs endpoint does not render anything that is sensitive. This endpoint just renders your chosen documentation viewer. The endpoint that has your API's details is the one that returns the JSON specification.
> 
> If you want to have security on these endpoints, you can disable the endpoints created by APIFairy and define your own. The `/docs` endpoint just uses open source documentation renderers, and the `/apispec.json` endpoint just returns `apifairy.apispec`.
> 
> I would imagine most API projects are not going to have a `@login_requred` decorator that they can use for this, or even a login form, so I'm not sure how common your request is. But I would be open to configure custom decorators to be added to these endpoints if that helps.

I would tend to agree that a private doc API is not very common perhaps but I can see the use of for example for an internal API.
You reckon overriding the blueprint routes is the cleanest way of getting the intended result?

**Comment by miguelgrinberg** [comment]
There is no need to override anything. You can configure this extension to not define those two routes, then you can write your own and use any auth that you like on them.
