### ISSUE TITLE
Response Decorator needs Jsonify method on schema?

### ISSUE THREAD

**Issue by jorgelaranjo** [miguelgrinberg/APIFairy#42]
The documentation does say:
> The decorator performs the serialization of the returned object or dictionary to JSON through the schema’s jsonify() method.
Looking at the `Microblog API` project however it seems to work in a different way?

Is it correct to say that the implementation of the `jsonify` method is not always required and if not how does it work?
Interesting when doing a `flask-sqlalchemy` `query.all()` and if the `jsonify` method is not implemented it returns `{}` but if using `query.first()` then it serializes just fine (and also applies the `@post_dump` decorator just fine).

How would one go about doing the same for a schema with a nested schema (list). It is possible without implement the `jsonify` method?

ref: #32

**Comment by miguelgrinberg** [comment]
@jorgelaranjo I don't understand issue are you referring to. The `jsonify()` method comes from Flask-Marshmallow schemas. Flask-Marshmallow is a required dependency of this extension.

**Comment by jorgelaranjo** [comment]
You mean, using something like this?

```
@blueprint.route("/endpoint/<string:id>", methods=['GET'])
@authenticate(auth)
@response(MySchema, 200)
def get_data(id):
    """ Get Data"""
    output = MyModel.query
    return output
```

in which case how do the @post_dump would go about re `timestamps` as usually it would be with the `@post_dump(pass_many=True)`?

And this is clearly `Flask-Marshmallow` and not so much `APIFairy` I'd guess.

**Comment by miguelgrinberg** [comment]
@jorgelaranjo I think you have some context about your project that I don't have, so I don't understand what the problem is with the timestamps.

Have you seen how I return posts in Microblog API? https://github.com/miguelgrinberg/microblog-api/blob/main/api/posts.py#L46. I just return a query. The post_dump in the schema works fine.
