### ISSUE TITLE
OpenAPI Info block - additional information not mandatory by spec.

### ISSUE THREAD

**Issue by jorgelaranjo** [miguelgrinberg/APIFairy#43]
After uploading an `apispec` file generated through `APIFairy` to `Stoplight` it does warn that the `info` block is missing the `contact` object.

Looking at the OpenAPI (Swagger) [spec](https://swagger.io/specification/) such block is not mandatory.
![image](https://user-images.githubusercontent.com/1196202/154802584-cbbbe292-62af-469a-9dcf-8de581748ac2.png)

Even minding this is not mandatory, would this something of added value to be added to config variables of `APIFairy`?
And if yes, would `termsOfService` and `license` also be adding value?

As this is really my requirement, I'm happy to do a PR with that update.

**Comment by miguelgrinberg** [comment]
You can use the [process_apispec](https://apifairy.readthedocs.io/en/latest/apifairy_class.html#apifairy-process-apispec) decorator to insert anything that the extension does not support directly.

**Comment by jorgelaranjo** [comment]
Thanks
