### ISSUE TITLE
Documetation not update with @arguments

### ISSUE THREAD

**Issue by duchuyvp** [miguelgrinberg/APIFairy#50]
Hi Miguel, I am working on a project and I decided to use APIFairy for documentation. Here is an example.

I have this schema for input and output for my endpoint and I use `arguments` decorator to describe input and output:

```python
class MyModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())

class MySchema(ma.SQLAlchemySchema):
    class Meta:
        model = MyModel
        load_instance = True
        include_fk = True

    id = ma.auto_field()
    title = ma.auto_field()

```

And I define my endpoint:

```python

@bp.route("/index", methods=["POST"])
@arguments(MySchema, location="form")
@response(MySchema)
def index(x):
    print(x)
    return x

```

After I run server, `apifairy.docs` works as usually but I don't see input describe for Request. 
I don't know how to config it, please help me!

Screenshot for `@arguments(MySchema, location="form")` (No describe for Request, works fine with `location="query"`)
![image](https://user-images.githubusercontent.com/93045745/176474962-0ded0bb5-497c-45a2-a6ac-49c047947c5f.png)

**Comment by duchuyvp** [comment]
I have read source code and see this `valid_locations`

```json
{
        "json": None,
        "form": None,
        "json_or_form": None,
        "querystring": ma.EXCLUDE,
        "query": ma.EXCLUDE,
        "headers": ma.EXCLUDE,
        "cookies": ma.EXCLUDE,
        "files": ma.EXCLUDE,
    }
```

How to config for each of them to show up on document page?
That's really helpful for me.

**Comment by miguelgrinberg** [comment]
My focus (so far, at least) was in JSON APIs. I haven't really tested or even tried to support forms. There is also another ticket regarding file uploads, which is also the same, I have not explored them yet.

I think this is definitely possible to do, but it needs to be investigated.

**Comment by duchuyvp** [comment]
I have read [`apiflask`'s source code](https://apiflask.com/usage/#use-appinput-to-validate-and-deserialize-request-data), hope it may helps you to find some ideas.

**Comment by miguelgrinberg** [comment]
Apiflask forked this project and took it in a complete different direction that involves an incredible amount of complexity. Not my thing.
