### ISSUE TITLE
How to use @response and set_cookie()?

### ISSUE THREAD

**Issue by Eliasmgprado** [miguelgrinberg/APIFairy#54]
As the @response decorator can`t aceept response objects, how can I create a route thats uses the set_cookie() function, and also has the @response decorator?

    @api.route("/foo")
    @response(BarSchema)
    def foo(bar):
        data = bar.get("foo")
        token = "123"
        response = jsonify(data)
        response.set_cookie(
            "fooToken",
            token,
            secure=False,
            httponly=True,
            samesite="Strict",
            path="/api/foo/tokens",
        )

        return response

This code return error: 

    The @response decorator cannot handle Response objects.

**Comment by miguelgrinberg** [comment]
Great question!

One option that you have is to add the `Set-Cookie` header directly, which does not prevent you from returning your schema based object:

```python
@api.route("/foo")
@response(BarSchema)
def foo():
    data = get_bar()
    token = "123"
    return data, 200, {'Set-Cookie': f'fooToken={token}; httpOnly; sameSite=strict; path=/api/foo/tokens'}
```

Another option would be to create an after_request handler and add the cookie there.

I hope these options work for you.

**Comment by Eliasmgprado** [comment]
Thanks, for that!

However the problem still continues for me, because in my case i need to set two cookies...
But I found this solution, if some one has the same issue...

    from werkzeug.datastructures import Headers
    from werkzeug.http import dump_cookie

    @api.route("/foo")
    @response(BarSchema)
    def foo(bar):
        data = bar.get("foo")
        token = "123"
        token2 = "456"

        headers = Headers()

        headers.add(
            "Set-Cookie",
            dump_cookie(
                "fooToken",
                token,
                secure=False,
                httponly=True,
                samesite="Strict",
                path="/api/foo/tokens",
        )

        headers.add(
            "Set-Cookie",
            dump_cookie(
                "fooToken2",
                token2,
                secure=False,
                httponly=True,
                samesite="Strict",
                path="/api/foo/tokens",
        )

        return response, 200, headers
