### ISSUE TITLE
Use both documentation format (swagger_ui and redoc) at the same time

### ISSUE THREAD

**Issue by eadomenech** [miguelgrinberg/APIFairy#6]
Is it possible to use both documentation format (swagger_ui and redoc) at the same time? How do I do it?

I would like to have them both in different ports of course.

**Comment by miguelgrinberg** [comment]
The swagger and redoc UIs are not part of this project, I just created two basic templates that load them from CDNs. You use these templates in your application in any way that you like. For example, you can mount the two documentation sites in the same application:

```python
@app.route('/swagger')
def swagger():
    return render_template('apifairy/swagger_ui.html', title=apifairy.title, version=apifairy.version)

@app.route('/redoc')
def redoc():
    return render_template('apifairy/redoc.html', title=apifairy.title, version=apifairy.version)
```

**Comment by eadomenech** [comment]
Done!!! Thank you.
