### ISSUE TITLE
specify schema for @other_responses

### ISSUE THREAD

**Issue by AdamVerner** [miguelgrinberg/APIFairy#60]
in the `@other_responses` decorator i can only specify string description but not the whole response body, that is only supported for the primary response.

Would be nice if i could also specify the other responses more closely so the user knows what data to expect even on failure.

**Comment by miguelgrinberg** [comment]
All your other responses across your API should use a single schema, the one for error responses, which is normally documented once. I would be okay providing a configuration option to define what schema to use for other responses, but I don't plan to support arbitrary schemas on these responses.

**Comment by AdamVerner** [comment]
i feel like it's a bummer, the specification supports it, so why not expose the functionality?

**Comment by miguelgrinberg** [comment]
The `@other_responses` decorator can now accept a schema instead of a string for each response. It can also accept both as a tuple.
