### ISSUE TITLE
Document headers

### ISSUE THREAD

**Issue by anilravuri** [miguelgrinberg/APIFairy#63]
Hi @miguelgrinberg ,

Do we support documenting headers? I looked at the documentation but could not find the information.

**Comment by miguelgrinberg** [comment]
Yes, this is supported via the `@arguments` decorator, by passing `location='headers'`. You are correct in that I should include an example of this in the docs, will update it in the next day or two.

**Comment by anilravuri** [comment]
Thanks @miguelgrinberg. Quick question - `@arguments` is only for a request right? What about documenting headers for a response? Like documenting the `Location` header on a 201 or 202.

Please let me know if I'm missing something obvious here.

**Comment by miguelgrinberg** [comment]
You are correct, the `@arguments` decorator is used to document headers in incoming requests. There is currently no decorator for response headers, but the `@response` could be extended to allow that.

The only way to add documentation for response headers is to insert that documentation manually in a `process_apispec` handler.

**Comment by miguelgrinberg** [comment]
@anilravuri I have added support for documenting request and response headers now. This is currently in the main branch. Can you please review it and let me know how this works for you?

**Comment by miguelgrinberg** [comment]
@anilravuri It's released now. Version 1.2.0. 🎉

**Comment by anilravuri** [comment]
Found a missing piece here - Should we add the same header support to `@other_responses` decorator as well?

**Comment by anilravuri** [comment]
> @anilravuri I'm not currently planning to extend `other_responses`.

Thank you for your response!
