### ISSUE TITLE
Add authentication to docs

### ISSUE THREAD

**Issue by hackzaid** [miguelgrinberg/APIFairy#66]
I would like to add login to the `apifairy.docs` so that only allowed/logged on users can access the documentation for my API.

I had tried adding `@login_required on`

```
@app.route('/') 
@login_required 
    def index():
        return redirect(url_for('apifairy.docs'))
```

but this couldn't find the set url on the `login.login_view = "dev_auth.login"`

What could be a better away to achive this as this is my first major API project and can't seem to find a work around

**Comment by miguelgrinberg** [comment]
APIFairy is designed to work on APIs, not on web applications. I don't plan to support standard cookie-based logins. Authentication with Flask-HTTPAuth is fully supported though, see the `@authenticate` decorator in the docs.
