### ISSUE TITLE
Using class methods as routes

### ISSUE THREAD

**Issue by franraknic** [miguelgrinberg/APIFairy#72]
Hi, first of all thanks for the great truly minimalistic API Documentation tool.

I have some legacy code that uses the blueprint `route` decorator on class methods. When I add APIFairy `arguments()` there are errors concerning positional params.

Example:
```
class ExmapleRequestSchema(ma.Schema):
    name = ma.Int(required=True, description="Name parameter description")

class ExampleResponseSchema(ma.Schema):
    name = ma.Str(description="Name response description")

class Example():

    data = "example data"
    
    @example_bp.route('/example', methods=['GET'])
    @arguments(ExmapleRequestSchema())
    @response(ExampleResponseSchema())
    def example(self, params): 
        '''Example endpoint'''
        response_data = {"name": self.data}
        response_schema = ExampleResponseSchema()
        return response_schema.dump(response_data)
```

The exception here being `"error": "example() missing 1 required positional argument: 'params'"`.
If I was to leave out the `params` then `self` is not a reference to the class itself but the query params!
This behaviour requires quiet alot of refactoring of the legacy classes or not using classes at all. Is there any way to declare class methods as routes but keep the method logic with referencing `self.data` or `self.some_function`?

**Comment by miguelgrinberg** [comment]
What value do you expect `self` to have? You don't have any instances of your `Example` class anywhere. As far as I can see your code is broken, even without the APIFairy decorators.

**Comment by franraknic** [comment]
This is true, my code is broken. I assumed that `Example` will be instantiated and that `self` will be a refrence to the instance.
I missed the part in the legacy code where it uses `Resource` from Flask-restful, in this case the `Example` class would subclass the `Resource` class from the extension and `self` would reference the object, the confusing part is that there is no instantiating  going on, at least not in the application code.
Is there any way of making this code work, as in making the `example` function see the classes  methos and attributes?

**Comment by miguelgrinberg** [comment]
@franraknic if you want something that is similar to Flask-RESTful you can use Flask's `MethodView` ([documentation](https://flask.palletsprojects.com/en/2.2.x/api/#flask.views.MethodView)). I don't use this in my projects though, and haven't tested or attempted to make APIFairy work with this structure. I might look into it at some point, but it isn't a priority for me because this is not a style that I use myself.

**Comment by franraknic** [comment]
I think the easiest way of refactoring the legacy code is to just instantiate the classes and use the results  in a separate function - that is described and documented with APIFairy.
Thank you very much for the replies and the advice, it pointed me in the right direction. Closing the issue.
