### ISSUE TITLE
Set API Base URL

### ISSUE THREAD

**Issue by cheizer** [miguelgrinberg/APIFairy#74]
How do I set the API Base URL for API Fairy? I'm using a reverse proxy via NGINX and it doesnt seem to be reading the headers since all of the docs are using 127.0.0.1:5000.

NGINX conf
```
location ^~ /api/ {
                proxy_pass http://127.0.0.1:5000/api/;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Prefix /;
        }
```

**Comment by miguelgrinberg** [comment]
Have you configured the `ProxyFix` middleware in your Flask app? That is what fixes the request when a reverse proxy is used.

**Comment by cheizer** [comment]
Yes, didnt seem do do anything.

```
from werkzeug.middleware.proxy_fix import ProxyFix

def create_app(config_class=Config):
	app = Flask(__name__)
	app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1)
```

**Comment by miguelgrinberg** [comment]
Try removing the `x_proto` option so that you get the defaults.

**Comment by cheizer** [comment]
I tried setting it to app.wsgi_app = ProxyFix(app.wsgi_app) and still no luck. Still shows 127.0.0.1:5000.

**Comment by cheizer** [comment]
Finally figured it out. It was the NGINX conf. I didnt have the following set.

```
proxy_redirect     off;
proxy_set_header   X-Real-IP            $remote_addr;
```
