### ISSUE TITLE
Issue with FileFIeld

### ISSUE THREAD

**Issue by dougclift** [miguelgrinberg/APIFairy#75]
When using a schema with FileField the file doesn't come through when I use the documentation endpoint.

It works in Postman so I can test there.  

In postman I'm using the multipart/form-data but on the documentation endpoint it lists application/x-www-form-urlencoded 

Is there a way to get the documentation endpoint to accept multipart/form-data?

I'm using @body(template_schema, location='form')

![image](https://user-images.githubusercontent.com/6352105/226129408-3f6fe623-a523-4287-8629-7998b033cdf5.png)

**Comment by miguelgrinberg** [comment]
Are you following the documentation? https://apifairy.readthedocs.io/en/latest/decorators.html#forms. In particular you should use APIFairy's own `FileField` in your schema.

**Comment by dougclift** [comment]
Yes.  I found the issue.  I had load_only=true in the FileField options.  Removing that I was able to upload the file using the documentation endpoint.
