### ISSUE TITLE
@body and hidden attributes 

### ISSUE THREAD

**Issue by cheizer** [miguelgrinberg/APIFairy#84]
Sorry, wasn't sure how to word the title. 

```python
class PostBodySchema(ma.Schema):
	class Meta:
		ordered = True
	
	serialNumber = ma.Str()
	UserID = ma.Str()
```

I would like to define my body schema but I would like to accept optional non-documented "hidden" attributes.  So in my post I would like to do the following ...

` { "serialNumber": "askjdhfklahs", "UserID":"001A", "ExtraData": "ALL"}`

When I submit this I get a error 400 "Unknown field."

Is there anyway around this?

**Comment by miguelgrinberg** [comment]
You can use the `unknown` parameter in the Marshmallow documentation? https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.Schema set to `marshmallow.INCLUDE`.

**Comment by cheizer** [comment]
Thanks, I will give it a go!
